### PR TITLE
Ran audit fix and update readme

### PR DESCRIPTION
**Pull request by kirubarajan**
- Ran `npm audit` and fixed unresolved vulnerabilities
- Updated insecure dependencies
- Added "gotcha" for npm environments to README

### CODE REVIEW

**Comment by kirubarajan** [comment]
Updating seems to break imports from `react-bootstrap`. Removing the `/lib` from the import path seems to resolve these errors. How should I proceed?

**Comment by VinaiRachakonda** [comment]
What does the import path look like then? Does the application render normally?

**Comment by kirubarajan** [comment]
The import paths end up being the same, but just without the `/lib/` subdirectory (i.e. just deleting `/lib` from paths will resolve them). 

This could be a big migration though, so I guess we can hold off on this until we have a more stable build.

**Comment by VinaiRachakonda** [comment]
Yeah I think it's a little high risk as well. Let's mark it as an issue and take care of it later.

**Pull request closed without merging**
