### PR TITLE
profile pictures in navigation

### PR DESCRIPTION
**Pull request by casey-chow**
When available, uses profile pictures in the navigation bar instead of the user email. This is meant to be used as an example of how profile pictures can be used in Magic Wand.

### CODE REVIEW

**Comment by albertzhidong** [comment]
I'm having trouble previewing this. it should appear once I enter a cloud hosted image (ex: https://i.ibb.co/TbTY7vS/Blog-Image-New.png) into the pic field no?

**Comment by casey-chow** [comment]
You need to nuke your database and re migrate

**Comment by albertzhidong** [comment]
remigrate with "make migrate" in magic-wand folder right?

**Comment by casey-chow** [comment]
Yeah.

**Review by VinaiRachakonda — APPROVED** [review]

**Pull request merged**
