### PR TITLE
Small fixes with ref map

### PR DESCRIPTION
**Pull request by VinaiRachakonda**

### CODE REVIEW

**Review by casey-chow — COMMENTED** [review]
Could you explain the try catch?

**Comment by casey-chow** [comment]
@VinaiRachakonda ^

**Comment by VinaiRachakonda** [comment]
Try and catch is so that I can just fill with empty string instead of losing the application completely. We can always just fix the company through the db.

**Review by casey-chow — APPROVED** [review]
Smart about the try/catch

**Pull request merged**
